apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cvmfs-atlas
provisioner: cvmfs.csi.cern.ch
parameters:
  repository: atlas.cern.ch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cvmfs-atlas-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-atlas
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - mountPath: /cvmfs/atlas.cern.ch
         name: atlas-pvc
  volumes:
   - name: atlas-pvc
     persistentVolumeClaim:
       claimName: csi-cvmfs-atlas-pvc
       readOnly: true
