apiVersion: v1
kind: Pod
metadata:
  name: test-harvester
spec:
  containers:
  - name: testkubeacces
    image: python:3-slim
    command: [
      sh,
      -c,
      "pip install kubernetes && tail -f /dev/null"
    ]
    volumeMounts:
    - mountPath: /sharedfs
      name: sharedfs
    # resources:
      # limits:
      #   cpu: '0.1'
      #   memory: '1Mi'
  volumes:
  - name: sharedfs
    hostPath:
      path: /var/sharedfs
